#! /bin/bash

#Make the folder structure for e. coli genomics project

# Note: bash needs to be run on the TRANSFER Cluster (TXFER)
# Data should hold all the original raw data and major intermediates
# Results holds the analytical outcomes, figure, etc.

# Make directories
# mkdir data results

# Copy over metadata
 cp /work/binf7960/instructor_data/Ecoli_metadata_composite.csv data/

# Retrieve raw data files
mkdir data/untrimmed_fastq
cd data/untrimmed_fastq
curl -O ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR258/004/SRR2589044/SRR2589044_1.fastq.gz
curl -O ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR258/004/SRR2589044/SRR2589044_2.fastq.gz
curl -O ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR258/003/SRR2584863/SRR2584863_1.fastq.gz
curl -O ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR258/003/SRR2584863/SRR2584863_2.fastq.gz
curl -O ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR258/006/SRR2584866/SRR2584866_1.fastq.gz
curl -O ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR258/006/SRR2584866/SRR2584866_2.fastq.gz
# cd ../../ 
